[project]
name = "person-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "namannb07", email = "namannb45@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "opencv-python>=5.0.0.93",
    "ultralytics>=8.4.126",
]

[project.scripts]
person-detection = "person_detection:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
